/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'intro',
    'repository-structure',
    'interview-format',
    'volunteers',
    {
      type: 'category',
      label: 'Volunteer Profiles',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'volunteers-profiles',
        },
      ],
    },
    'contributing',
  ],
};

module.exports = sidebars;
